version: 2

models:
  - name: sppo_vistoria_tr_subtt_cglf_2023_staging
    description: "sppo_vistoria_tr_subtt_cglf_2023"
    columns:
      - name: data
        description: "Data da captura"
      - name: id_veiculo
        description: "Número de ordem do veículo, identificação que é exibida na lateral do ônibus"
      - name: placa
        description: "Placa do veículo"
      - name: permissao
        description: "Número da permissão do ônibus"
      - name: chassi
        description: "Chassi do veículo"
      - name: ano_fabricacao
        description: "Ano de fabricação do veículo"
      - name: selo
        description: "Selo"
      - name: darm
        description: "Código do Documento de Arrecadação de Receitas Municipais"
      - name: ano_ultima_vistoria
        description: "Ano da última vistoria realizada pelo veículo"
  - name: sppo_vistoria_tr_subtt_cglf_2024_staging
    description: "sppo_vistoria_tr_subtt_cglf_2024"
    columns:
      - name: data
        description: "Data da captura"
      - name: id_veiculo
        description: "Número de ordem do veículo, identificação que é exibida na lateral do ônibus"
      - name: placa
        description: "Placa do veículo"
      - name: permissao
        description: "Número da permissão do ônibus"
      - name: chassi
        description: "Chassi do veículo"
      - name: ano_fabricacao
        description: "Ano de fabricação do veículo"
      - name: selo
        description: "Selo"
      - name: darm
        description: "Código do Documento de Arrecadação de Receitas Municipais"
      - name: ano_ultima_vistoria
        description: "Ano da última vistoria realizada pelo veículo"
  - name: sppo_vistoria_tr_subtt_cglf_pendentes_2024_staging
    description: "sppo_vistoria_tr_subtt_cglf_pendentes_2024"
    columns:
      - name: data
        description: "Data da captura"
      - name: id_veiculo
        description: "Número de ordem do veículo, identificação que é exibida na lateral do ônibus"
      - name: placa
        description: "Placa do veículo"
      - name: permissao
        description: "Número da permissão do ônibus"
      - name: empresa
        description: "Empresa ao qual o veículo está vinculado"
      - name: ano_ultima_vistoria
        description: "Ano da última vistoria realizada pelo veículo"
  - name: sppo_licenciamento_stu_staging
    description: "View de Dados cadastrais dos veículos que operam o sistema de ônibus (BRT e SPPO) no município do Rio de Janeiro.\n
    Dados capturados diariamente de: https://www.data.rio/documents/c6c97d3c15434b5088965e25f85e27c3"
    columns:
      - name: data
        description: "Data da captura (partição)"
      - name: timestamp_captura
        description: "Timestamp de captura dos dados de licenciamento"
      - name: modo
        description: "ÔNIBUS – nesse arquivo só constam os ônibus"
      - name: id_veiculo
        description: "Número de ordem do veículo, identificação que é exibida na lateral do ônibus"
      - name: ano_fabricacao
        description: "Ano de fabricação do veículo"
      - name: carroceria
        description: "Descrição do modelo da carroceria"
      - name: data_ultima_vistoria
        description: "Data da última vistoria do veículo"
      - name: id_carroceria
        description: "Código do modelo da carroceria"
      - name: id_chassi
        description: "Código do modelo do chassi"
      - name: id_fabricante_chassi
        description: "Identificador do fabricante do chassi"
      - name: id_interno_carroceria
        description: "Código interno do modelo de carroceria"
      - name: id_planta
        description: "Código da planta do veículo"
      - name: indicador_ar_condicionado
        description: "Indicador se possui ar condicionado (Verdadeiro/Falso)"
      - name: indicador_elevador
        description: "Indicador se possui elevador (Verdadeiro/Falso)"
      - name: indicador_usb
        description: "Indicador se tem USB (Verdadeiro/Falso)"
      - name: indicador_wifi
        description: "Indicador se tem Wi-fi (Verdadeiro/Falso)"
      - name: nome_chassi
        description: "Descrição do modelo do chassi"
      - name: permissao
        description: "Número da permissão do ônibus"
      - name: placa
        description: "Placa do veículo"
      - name: quantidade_lotacao_pe
        description: "Quantidade de passageiros em pé"
      - name: quantidade_lotacao_sentado
        description: "Quantidade de passageiros sentados"
      - name: tipo_combustivel
        description: "Combustível utilizado"
      - name: tipo_veiculo
        description: "Tipo de veículo"
      - name: status
        description: "Licenciado - Veículo licenciado no Sistema de Transporte Urbano (STU)"
      - name: data_inicio_vinculo
        description: "Data de início do vínculo do veículo no STU"
  - name: sppo_infracao_staging
    description: "View de todas as multas aplicadas aos modos de transporte no município do Rio de Janeiro, com qualquer situação.
    Dados capturados diariamente de: https://www.data.rio/documents/multas-aplicadas-aos-modos-de-transporte-nos-%C3%BAltimos-cinco-anos"
    columns:
      - name: data
        description: "Data da captura (partição)"
      - name: timestamp_captura
        description: "Timestamp de captura dos dados de infração"
      - name: modo
        description: "ÔNIBUS – nesse arquivo só constam os ônibus"
      - name: permissao
        description: "Número da permissão do ônibus"
      - name: placa
        description: "Placa do veículo"
      - name: id_auto_infracao
        description: "Identificador do auto de infração da multa aplicada"
      - name: data_infracao
        description: "Data da infração"
      - name: valor
        description: "Valor devido (R$)"
      - name: id_infracao
        description: "Código da infração"
      - name: infracao
        description: "Descrição da infração"
      - name: status
        description: "CADASTRADA - Registrada no sistema sem guia de pagamento\n
                      EM ABERTO - Com guia de pagamento e dentro do prazo de vencimento\n
                      VENCIDA - Com guia de pagamento e fora do prazo de vencimento\n
                      EM RECURSO - Possui Processo de Recurso aguardando julgamento\n
                      PAGA - Com guia de pagamento efetivamente paga\n
                      CANCELADA - Multa foi cancelada através de um Processo de Recurso"
      - name: data_pagamento
        description: "Data de pagamento"
  - name: sppo_licenciamento_solicitacao_staging
    description: "View de dados cadastrais das solicitações em andamento para ingresso no Sistema de Transporte Urbano (STU)"
    columns:
      - name: data
        description: "Data da captura (partição)"
      - name: timestamp_captura
        description: "Timestamp de captura dos dados de licenciamento"
      - name: modo
        description: "ÔNIBUS – nesse arquivo só constam os ônibus"
      - name: id_veiculo
        description: "Número de ordem do veículo, identificação que é exibida na lateral do ônibus"
      - name: ano_fabricacao
        description: "Ano de fabricação do veículo"
      - name: carroceria
        description: "Descrição do modelo da carroceria"
      - name: data_ultima_vistoria
        description: "Data da última vistoria do veículo"
      - name: id_carroceria
        description: "Código do modelo da carroceria"
      - name: id_chassi
        description: "Código do modelo do chassi"
      - name: id_fabricante_chassi
        description: "Identificador do fabricante do chassi"
      - name: id_interno_carroceria
        description: "Código interno do modelo de carroceria"
      - name: id_planta
        description: "Código da planta do veículo"
      - name: indicador_ar_condicionado
        description: "Indicador se possui ar condicionado (Verdadeiro/Falso)"
      - name: indicador_elevador
        description: "Indicador se possui elevador (Verdadeiro/Falso)"
      - name: indicador_usb
        description: "Indicador se tem USB (Verdadeiro/Falso)"
      - name: indicador_wifi
        description: "Indicador se tem Wi-fi (Verdadeiro/Falso)"
      - name: nome_chassi
        description: "Descrição do modelo do chassi"
      - name: permissao
        description: "Número da permissão do ônibus"
      - name: placa
        description: "Placa do veículo"
      - name: quantidade_lotacao_pe
        description: "Quantidade de passageiros em pé"
      - name: quantidade_lotacao_sentado
        description: "Quantidade de passageiros sentados"
      - name: tipo_combustivel
        description: "Combustível utilizado"
      - name: tipo_veiculo
        description: "Tipo de veículo"
      - name: status
        description: "Inválido - Veículo com solicitação inválida para ingresso no Sistema de Transporte Urbano (STU)\n
                      Válido - Veículo com solicitação válida para ingresso no Sistema de Transporte Urbano (STU)"
      - name: solicitacao
        description: "Inclusão - Solicitação de ingresso de veículo no Sistema de Transporte Urbano (STU)\n
                      Baixa - Solicitação de baixa de veículo já incluído no Sistema de Transporte Urbano (STU)\n
                      Renumeração - Solicitação de alteração de número de ordem de veículo já incluído no Sistema de Transporte Urbano (STU)"
  - name: sppo_registro_agente_verao_staging
    description: "View com registros de Agentes de Verão para fins de cálculo de subsídio nos termos da RESOLUÇÃO SMTR Nº 3.682/2024"
    columns:
      - name: data
        description: "Data de registro pelo agente público"
      - name: datetime_registro
        description: "Datetime de registro pelo agente público"
      - name: id_registro
        description: "ID do registro (HASH SHA256)"
      - name: id_veiculo
        description: "Número de ordem do veículo, identificação que é exibida na lateral do ônibus"
      - name: servico
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, SN011, ...)"
      - name: link_foto
        description: "Link com a imagem interna do veículo"
      - name: validacao
        description: "Coluna de validação do registro enviado pelo agente público (apenas TRUE nesta tabela)"
      - name: datetime_captura
        description: "Datetime de captura do registro pela pipeline"
      - name: versao
        description: "SHA do repositório no Github"