# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "rj_smtr"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +persist_docs:
    relation: true
    columns: true
  rj_smtr:
    # Config indicated by + and applies to all files under models/example/
    projeto_subsidio_sppo:
      +materialized: view # Materialization type (view, table or incremental)
      +schema: projeto_subsidio_sppo # Overrides the default schema (defaults to what is set on profiles.yml)

vars:

  # General tables (please keep on alphabetical order)
  gps_sppo: "`rj-smtr.br_rj_riodejaneiro_veiculos.gps_sppo`"
  sigmob_data_versao: "`rj-smtr-dev.br_rj_riodejaneiro_sigmob.data_versao_efetiva`"
  sigmob_routes: "`rj-smtr-dev.br_rj_riodejaneiro_sigmob.routes_desaninhada`"
  sigmob_shapes: "`rj-smtr-dev.br_rj_riodejaneiro_sigmob.shapes_geom`"
  
  # Dataset: projeto_subsidio_sppo
  # => Model version
  projeto_subsidio_sppo_version: "projeto_subsidio_sppo_v1.0.0"
  # => Parameters
  run_date: "2022-05-20"
  buffer: 500 # distância em metros para buffer
  perc_conformidade_distancia_min: 80
  perc_conformidade_shape_min: 80
  perc_conformidade_registros_min: 60
  perc_distancia_total_subsidio: 80
  quadro_horario_dia_util: "`rj-smtr-dev.projeto_subsidio_sppo.quadro_horario_dia_util`"
  valor_subsidio: "`rj-smtr-dev.projeto_subsidio_sppo.valor_subsidio`"
