# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "rj_smtr"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

vars:
  ### SIGMOB
  data_inclusao_agency: "2021-08-03"
  data_inclusao_stop_times: "2021-08-03"
  data_inclusao_linhas: "2021-08-03"
  data_inclusao_routes: "2021-08-03"
  data_inclusao_trips: "2021-08-03"
  data_inclusao_shapes: "2021-08-24"
  data_inclusao_stops: "2021-08-24"
  data_inclusao_calendar: "2021-09-30"
  data_inclusao_frota_determinada: "2021-09-30"
  data_inclusao_stop_details: "2021-09-30"
  data_inclusao_holidays: "2021-11-05"

  agency_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.agency"
  calendar_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.calendar"
  frota_determinada_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.frota_determinada"
  holidays_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.holidays"
  linhas_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.linhas"
  routes_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.routes"
  shapes_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.shapes"
  shapes_geom_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.shapes_geom"
  stop_times_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.stop_times"
  stop_details_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.stop_details"
  stops_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.stops"
  trips_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.trips"

  ### BRT
  # Parametros de intersecção do ônibus com rota
  ## Tamanho do buffer da rota
  tamanho_buffer_metros: 100 # flag_trajeto_correto
  ## Intervalo máximo que um veículo pode ficar fora da rota para ser considerado
  ## dentro da rota. Afeta a flag flag_trajeto_correto_hist
  intervalo_max_desvio_segundos: 600 # flag_trajeto_correto
  ## Tamanho da janela de tempo (em segundos) para cálculo da média móvel de velocidade do veículo
  janela_movel_velocidade: 600 # aux_registros_velocidade
  ## velocidade máxima média que o veículo pode atingir para evitar outliers provenientes de túneis
  velocidade_maxima: 60
  ## Velocidade mínima para que o carro seja considerado em movimento em aux_registros_velocidade
  velocidade_limiar_parado: 3
  ## Distância mínima para que o veículo seja identificado parado em um terminal ou garagem em aux_registros_parada
  distancia_limiar_parada: 250

  # dependências de views/tabelas
  brt_registros: rj-smtr-staging.br_rj_riodejaneiro_brt_gps_staging.registros
  limites_caixa: "rj-smtr.br_rj_riodejaneiro_geo.limites_geograficos_caixa" # registros_filtrada
  brt_terminais: "rj-smtr.br_rj_riodejaneiro_transporte.estacoes_e_terminais_brt" # aux_registros_parada
  polygon_garagem: "rj-smtr.br_rj_riodejaneiro_geo.garagens_polygon" # aux_registros_parada

  ### SPPO
  sppo_id_modal_smtr: ["'22'", "'23'", "'O'"]
  linhas_sppo: "rj-smtr.br_rj_riodejaneiro_transporte.linhas_sppo" # registros_agg_data_hora_consorcio

  # dependencias de views/tabelas
  sppo_terminais: "rj-smtr.br_rj_riodejaneiro_transporte.terminais_onibus_coordenadas" # aux_registros_parada

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +persist_docs:
    relation: true
    columns: true
  rj_smtr:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view # Materialization type (view, table or incremental)
      +schema: example # Overrides the default schema (defaults to what is set on profiles.yml)
    br_rj_riodejaneiro_sigmob:
      +materialized: view
      +schema: br_rj_riodejaneiro_sigmob
    br_rj_riodejaneiro_onibus_gps:
      +materialized: view
      +schema: br_rj_riodejaneiro_onibus_gps
    br_rj_riodejaneiro_brt_gps:
      +materialized: view
      +schema: br_rj_riodejaneiro_brt_gps
    br_rj_riodejaneiro_veiculos:
      +materialized: view
      +schema: br_rj_riodejaneiro_veiculos
