name: "rj_smtr"
version: "1.0.0"
config-version: 2

profile: "default"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

vars:
  ### Date default variables ###
  date_range_start: "2022-01-01T00:00:00"
  date_range_end: "2022-01-01T01:00:00"
  start_date: "2022-01-01T01:00:00"
  end_date: "2022-01-01T01:00:00"
  run_date: "2022-01-01T01:00:00"

  ### Version default variable (replaced on deploy) ###
  version: ""

  ### GPS ###
  brt_terminais: "rj-smtr.br_rj_riodejaneiro_transporte.estacoes_e_terminais_brt" # aux_registros_parada
  brt_registros_staging: rj-smtr-staging.br_rj_riodejaneiro_brt_gps_staging.registros
  limites_caixa: "rj-smtr.br_rj_riodejaneiro_geo.limites_geograficos_caixa" # registros_filtrada
  linhas_sppo: "rj-smtr.br_rj_riodejaneiro_transporte.linhas_sppo" # registros_agg_data_hora_consorcio
  polygon_garagem: "rj-smtr.br_rj_riodejaneiro_geo.garagens_polygon" # aux_registros_parada
  sppo_terminais: "rj-smtr.br_rj_riodejaneiro_transporte.terminais_onibus_coordenadas" # aux_registros_parada
  sppo_registros_staging: "rj-smtr-staging.br_rj_riodejaneiro_onibus_gps_staging.registros"
  sppo_realocacao_staging: "rj-smtr-staging.br_rj_riodejaneiro_onibus_gps_staging.realocacao"
  data_inicio_realocacao: "2022-11-15"

  # Parametros de intersecção do ônibus com rota
  ## Tamanho do buffer da rota
  tamanho_buffer_metros: 500 # flag_trajeto_correto
  ## Intervalo máximo que um veículo pode ficar fora da rota para ser considerado
  ## dentro da rota. Afeta a flag flag_trajeto_correto_hist
  intervalo_max_desvio_segundos: 600 # flag_trajeto_correto
  ## Tamanho da janela de tempo (em segundos) para cálculo da média móvel de velocidade do veículo
  janela_movel_velocidade: 600 # aux_registros_velocidade
  ## Velocidade máxima média que o veículo pode atingir para evitar outliers provenientes de túneis
  velocidade_maxima: 60
  ## Velocidade mínima para que o carro seja considerado em movimento em aux_registros_velocidade
  velocidade_limiar_parado: 3
  ## Distância mínima para que o veículo seja identificado parado em um terminal ou garagem em aux_registros_parada
  distancia_limiar_parada: 250

  ### [ANTIGO] SIGMOB ###

  # Modal SPPO (ônibus)
  sppo_id_modal_smtr: ["'22'", "'23'", "'O'"]

  # Modal BRT
  brt_id_modal_smtr: ["'20'", "'B'"]

  # data_versao fixada para operações que envolvem o uso do SIGMOB
  versao_fixa_sigmob: "2022-06-10"

  data_inclusao_agency: "2021-08-03"
  data_inclusao_stop_times: "2021-08-03"
  data_inclusao_linhas: "2021-08-03"
  data_inclusao_routes: "2021-08-03"
  data_inclusao_trips: "2021-08-03"
  data_inclusao_shapes: "2021-08-24"
  data_inclusao_stops: "2021-08-24"
  data_inclusao_calendar: "2021-09-30"
  data_inclusao_frota_determinada: "2021-09-30"
  data_inclusao_stop_details: "2021-09-30"
  data_inclusao_holidays: "2021-11-05"

  agency_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.agency"
  calendar_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.calendar"
  frota_determinada_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.frota_determinada"
  holidays_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.holidays"
  linhas_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.linhas"
  routes_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.routes"
  shapes_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.shapes"
  shapes_geom_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.shapes_geom"
  stop_times_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.stop_times"
  stop_details_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.stop_details"
  stops_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.stops"
  trips_staging: "rj-smtr-staging.br_rj_riodejaneiro_sigmob_staging.trips"

  ## GTFS
  data_versao_gtfs: "YYYY-MM-DD"

  ### Subsídio SPPO (Ônibus) ###
  buffer: 500 # distância em metros para buffer
  perc_conformidade_distancia_min: 0
  perc_conformidade_shape_min: 80
  perc_conformidade_registros_min: 50
  perc_distancia_total_subsidio: 80
  quadro_horario: "`rj-smtr-staging.projeto_subsidio_sppo_staging.quadro_horario`"
  subsidio_shapes: "`rj-smtr-staging.projeto_subsidio_sppo_staging.shapes`"
  subsidio_trips: "`rj-smtr-staging.projeto_subsidio_sppo_staging.trips`"
  subsidio_parametros: "`rj-smtr-staging.dashboard_subsidio_sppo_staging.subsidio_parametros`"
  shapes_version: "YYYY-MM-DD"
  frequencies_version: "YYYY-MM-DD"
  DATA_SUBSIDIO_V2_INICIO: "2023-01-16"
  DATA_SUBSIDIO_V3_INICIO: "2023-07-16"
  # valor_subsidio: "`rj-smtr-dev.projeto_subsidio_sppo.valor_subsidio`"

  # Recursos #
  recurso_staging: "rj-smtr-staging.projeto_subsidio_sppo_staging.recurso"
  recurso_prazo: "rj-smtr.projeto_subsidio_sppo.recurso_prazo"
  recurso_julgamento: "rj-smtr.projeto_subsidio_sppo.recurso_julgamento"
  recurso_viagem_start: "2022-07-01 00:00:00"
  recurso_viagem_end: "2022-07-15 00:00:00"
  recurso_timestamp_captura: "2022-11-04T14:17:00"
  perc_conformidade_distancia_recurso_min: 50

  ### Veiculos ###
  sppo_licenciamento_stu_staging: "rj-smtr-staging.veiculo_staging.sppo_licenciamento_stu"
  sppo_licenciamento_solicitacao_staging: "rj-smtr-staging.veiculo_staging.sppo_licenciamento_solicitacao"
  sppo_infracao_staging: "rj-smtr-staging.veiculo_staging.sppo_infracao"
  sppo_registro_agente_verao_staging: "rj-smtr-staging.veiculo_staging.sppo_registro_agente_verao"
  sppo_licenciamento_solicitacao_data_versao: "2023-02-06"
  stu_data_versao: ""

  ### RDO ###
  rho_registros_sppo_staging: "rj-smtr-staging.br_rj_riodejaneiro_rdo_staging.rho_registros_sppo"
  rho_max_processing_interval: 7
  rho_sppo_start_date: "2021-03-01"

  ### Bilhetagem ###
  var_percentual_tarifa_cbd: 0.04
  quantidade_integracoes_max: 5
  colunas_integracao: {
    "data_transacao": {"type": "DATETIME", "select": true},
    "id_aplicacao": {"type": "ID", "select": false},
    "id_consorcio": {"type": "ID", "select": true},
    "id_emissor": {"type": "ID", "select": false},
    "id_linha": {"type": "ID", "select": true},
    "id_matriz_integracao": {"type": "ID", "select": false},
    "id_operadora": {"type": "ID", "select": true},
    "id_ordem_rateio": {"type": "ID", "select": false},
    "id_secao": {"type": "STRING", "select": false},
    "id_servico": {"type": "ID", "select": false},
    "id_tipo_modal": {"type": "ID", "select": true},
    "id_transacao": {"type": "STRING", "select": true},
    "latitude_trx": {"type": "FLOAT64", "select": false},
    "longitude_trx": {"type": "FLOAT64", "select": false},
    "nr_logico_midia_operador": {"type": "STRING", "select": false},
    "perc_rateio": {"type": "FLOAT64", "select": true},
    "posicao_validador": {"type": "STRING", "select": false},
    "sentido": {"type": "ID", "select": true},
    "valor_rateio_compensacao": {"type": "FLOAT64", "select": true},
    "valor_rateio": {"type": "FLOAT64", "select": true},
    "valor_tarifa": {"type": "FLOAT64", "select": true},
    "valor_transacao": {"type": "FLOAT64", "select": true},
    "veiculo_id": {"type": "ID", "select": false},
  }

  ### Diretorios ###
  ids_consorcios: {"'221000014'": "'6'", "'221000023'": "'4'", "'221000032'": "'3'", "'221000041'": "'5'", "'221000050'": "'1'"}

  ### Diretorios ###
  ids_consorcios: ["'221000014'", "'221000023'", "'221000032'", "'221000041'", "'221000050'"] 

models:
  +persist_docs:
    relation: true
    columns: true
  rj_smtr:
    projeto_subsidio_sppo:
      +materialized: view
      +schema: projeto_subsidio_sppo
    br_rj_riodejaneiro_gtfs:
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +schema: br_rj_riodejaneiro_gtfs
    br_rj_riodejaneiro_sigmob:
      +materialized: view
      +schema: br_rj_riodejaneiro_sigmob
    br_rj_riodejaneiro_onibus_gps:
      +materialized: view
      +schema: br_rj_riodejaneiro_onibus_gps
    br_rj_riodejaneiro_brt_gps:
      +materialized: view
      +schema: br_rj_riodejaneiro_brt_gps
    br_rj_riodejaneiro_veiculos:
      +materialized: view
      +schema: br_rj_riodejaneiro_veiculos
    dashboard_subsidio_sppo:
      +materialized: view
      +schema: dashboard_subsidio_sppo
    veiculo:
      +materialized: view
      +schema: veiculo
    br_rj_riodejaneiro_rdo:
      +materialized: view
      +schema: br_rj_riodejaneiro_rdo
    br_rj_riodejaneiro_rdo_staging:
      +materialized: view
      +schema: br_rj_riodejaneiro_rdo_staging
    br_rj_riodejaneiro_stu:
      +materialized: view
      +schema: br_rj_riodejaneiro_stu
    br_rj_riodejaneiro_recursos:
      +materialized: incremental
      +schema: br_rj_riodejaneiro_recursos
    br_rj_riodejaneiro_recursos_staging:
      +materialized: incremental
      +schema: br_rj_riodejaneiro_recursos_staging
