version: 2

models:
  - name: rho_registros_sppo
    description: "Tabela materializada para acesso geral aos dados do RHO SPPO"
    columns:
      - name: data_transacao
        description: "Data da transação (partição)"
      - name: hora_transacao
        description: "Hora da transação"
      - name: data_processamento
        description: "Data de processamento da transação"
      - name: data_arquivo_rho
        description: "Data do arquivo fonte do RHO"
      - name: servico_riocard
        description: "Nome curto da linha de acordo com o padrão do RioCard"
      - name: linha_riocard
        description: "Identificador interno da linha no RioCard"
      - name: operadora
        description: "Identificador da operadora de transporte"
      - name: quantidade_transacao_cartao
        description: "Quantidade de transações feitas com o cartão"
      - name: quantidade_transacao_especie
        description: "Quantidade de transações feitas em espécie"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de gratuidades"
      - name: registro_processado
        description: "Identificador se o registro foi recalculado"
      - name: datetime_captura
        description: "Data e hora da captura dos dados"

  - name: rho_registros_stpl
    description: "Tabela materializada para acesso geral aos dados do RHO STPL"
    columns:
      - name: data_transacao
        description: "Data da transação (partição)"
      - name: hora_transacao
        description: "Hora da transação"
      - name: servico_riocard
        description: "Nome curto da linha de acordo com o padrão do RioCard"
      - name: operadora
        description: "Identificador da operadora de transporte"
      - name: quantidade_transacao_pagante
        description: "Quantidade de transações pagantes"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de gratuidades"
      - name: arquivos_somados
        description: "Coluna de controle com array das datas dos arquivos que foram somados para obter os valores finais"