version: 2

models:
  - name: encontro_contas_consorcio_ano_2023_cenario_1
    description: "Sumário Encontro de Contas por Consórcio - Cenário 1 (2023)"
    columns:
      - name: ano
        description: "Ano"
      - name: consorcio
        description: "Nome do consórcio"
      - name: km_milhoes
        description: "Quilometragem apurada - km (milhões)"
      - name: remuneracao_tarifaria_milhoes
        description: "Remuneração tarifária - R$ (milhões)"
      - name: subsidio_milhoes
        description: "Subsídio apurado - R$ (milhões)"
      - name: receita_aferida_milhoes
        description: "Receita total aferida - R$ (milhões)"
      - name: receita_esperada_milhoes
        description: "Receita total esperada - R$ (milhões)"
      - name: desconto_milhoes
        description: "Desconto total - R$ (milhões)"
      - name: saldo
        description: "Saldo total - R$ (milhões)"
  - name: encontro_contas_consorcio_ano_2023_cenario_2
    description: "Sumário Encontro de Contas por Consórcio - Cenário 0 (2023)"
    columns:
      - name: ano
        description: "Ano"
      - name: consorcio
        description: "Nome do consórcio"
      - name: km_milhoes
        description: "Quilometragem apurada - km (milhões)"
      - name: remuneracao_tarifaria_milhoes
        description: "Remuneração tarifária - R$ (milhões)"
      - name: subsidio_milhoes
        description: "Subsídio apurado - R$ (milhões)"
      - name: receita_aferida_milhoes
        description: "Receita total aferida - R$ (milhões)"
      - name: receita_esperada_milhoes
        description: "Receita total esperada - R$ (milhões)"
      - name: desconto_milhoes
        description: "Desconto total - R$ (milhões)"
      - name: saldo
        description: "Saldo total - R$ (milhões)"
  - name: subsidio_parametros_atualizada
    description: "Parâmetros de remuneração do subsídio dos serviços de ônibus (SPPO) por tipo de viagem"
    columns:
      - name: indicador_licenciado
        description: "Indicador se o veículo encontra-se licenciado"
      - name: indicador_ar_condicionado
        description: "Indicador se o veículo foi licenciado com ar condicionado"
      - name: indicador_autuacao_ar_condicionado
        description: "Indicador se o veículo foi autuado por inoperância ou mau funcionamento do sistema de ar condicionado"
      - name: indicador_autuacao_seguranca
        description: "Indicador se o veículo foi autuado por infração relacionada à segurança do veículo"
      - name: indicador_autuacao_limpeza
        description: "Indicador se o veículo foi autuado por infração relacionada à limpeza do veículo"
      - name: indicador_autuacao_equipamento
        description: "Indicador se o veículo foi autuado por infração relacionada à inoperância ou mau funcionamento de equipamentos do veículo"
      - name: indicador_sensor_temperatura
        description: "Indicador se o sensor de temperatura do veículo não estava em funcionamento conforme especificação da SMTR"
      - name: indicador_validador_sbd
        description: "Indicador se o veículo se encontra com o novo validador do Sistema de Bilhetagem Digital (SBD) instalado"
      - name: status
        description: "Classificação, observados os demais parâmetros - Categorias:\n
        - Não licenciado\n
        - Autuado por ar inoperante\n
        - Autuado por segurança\n
        - Autuado por limpeza/equipamento\n
        - Sem ar e não autuado\n
        - Com ar e não autuado"
      - name: subsidio_km
        description: "Valor de subsídio de remuneração (R$/km)"
      - name: irk
        description: "Índice de Remuneração por km (R$/km)"
      - name: data_inicio
        description: "Data inicial do período de vigência dos demais atributos"
      - name: data_fim
        description: "Data final do período de vigência dos demais atributos"
      - name: legislacao
        description: "Legislação que estabelece o valor e regras de remuneração"
      - name: ordem
        description: "Ordem de prioridade de aplicação dos valores de remuneração"
