version: 2

models:
  - name: balanco_consorcio_ano
    description: "Balanço da receita aferida e esperada por consórcio e
    ano para serviços-dia subsidiados. Ver metodologia em NOTA TÉCNICA TR/SUBTT Nº 01/2024"
    columns:
      - name: ano
        description: "Ano"
      - name: consorcio
        description: "Consórcio"
      - name: km_subsidiada
        description: "Quilometragem apurada e subsidiada via algoritmo [km]"
      - name: receita_total_esperada
        description: "Receita total esperada com base na quilometragem (IRK x km) [R$]"
      - name: receita_tarifaria_esperada
        description: "Receita tarifária esperada com base na quilometragem [R$]"
      - name: subsidio_esperado
        description: "Subsídio esperado com base na quilometragem [R$]"
      - name: subsidio_glosado
        description: "Subsídio glosado conforme os decretos e resoluções vigentes [R$]"
      - name: receita_total_aferida
        description: "Receita total aferida (receita tarifária + subsidio pago) [R$]"
      - name: receita_tarifaria_aferida
        description: "Receita tarifária aferida com base no RDO informado pelos consórcios [R$]"
      - name: subsidio_pago
        description: "Subsídio pago [R$]"
      - name: saldo
        description: "Saldo entre a receita esperada e aferida, descontado o subsídio glosado [R$]"
  - name: balanco_consorcio_dia
    description: "Balanço da receita aferida e esperada por consórcio e
    dia para serviços-dia subsidiados. Ver metodologia em NOTA TÉCNICA TR/SUBTT Nº 01/2024"
    columns:
      - name: data
        description: "Data"
      - name: consorcio
        description: "Consórcio"
      - name: km_subsidiada
        description: "Quilometragem apurada e subsidiada via algoritmo [km]"
      - name: receita_total_esperada
        description: "Receita total esperada com base na quilometragem (IRK x km) [R$]"
      - name: receita_tarifaria_esperada
        description: "Receita tarifária esperada com base na quilometragem [R$]"
      - name: subsidio_esperado
        description: "Subsídio esperado com base na quilometragem [R$]"
      - name: subsidio_glosado
        description: "Subsídio glosado conforme os decretos e resoluções vigentes [R$]"
      - name: receita_total_aferida
        description: "Receita total aferida (receita tarifária + subsidio pago) [R$]"
      - name: receita_tarifaria_aferida
        description: "Receita tarifária aferida com base no RDO informado pelos consórcios [R$]"
      - name: subsidio_pago
        description: "Subsídio pago [R$]"
      - name: saldo
        description: "Saldo entre a receita esperada e aferida,
        descontado o subsídio glosado [R$]"
  - name: balanco_servico_ano
    description: "Balanço da receita aferida e esperada por serviço e
    ano para serviços-dia subsidiados. Ver metodologia em NOTA TÉCNICA TR/SUBTT Nº 01/2024"
    columns:
      - name: ano
        description: "Ano"
      - name: servico
        description: "Serviço"
      - name: km_subsidiada
        description: "Quilometragem apurada e subsidiada via algoritmo [km]"
      - name: receita_total_esperada
        description: "Receita total esperada com base na quilometragem (IRK x km) [R$]"
      - name: receita_tarifaria_esperada
        description: "Receita tarifária esperada com base na quilometragem [R$]"
      - name: subsidio_esperado
        description: "Subsídio esperado com base na quilometragem [R$]"
      - name: subsidio_glosado
        description: "Subsídio glosado conforme os decretos e resoluções vigentes [R$]"
      - name: receita_total_aferida
        description: "Receita total aferida (receita tarifária + subsidio pago) [R$]"
      - name: receita_tarifaria_aferida
        description: "Receita tarifária aferida com base no RDO informado pelos consórcios [R$]"
      - name: subsidio_pago
        description: "Subsídio pago [R$]"
      - name: saldo
        description: "Saldo entre a receita esperada e aferida, descontado o subsídio glosado [R$]"
  - name: balanco_servico_dia
    description: "Balanço da receita aferida e esperada por servico e
    dia para serviços-dia subsidiados. Ver metodologia em NOTA TÉCNICA TR/SUBTT Nº 01/2024"
    columns:
      - name: data
        description: "Data"
      - name: consorcio
        description: "Consórcio"
      - name: servico
        description: "Serviço"
      - name: km_subsidiada
        description: "Quilometragem apurada e subsidiada via algoritmo [km]"
      - name: receita_total_esperada
        description: "Receita total esperada com base na quilometragem (IRK x km) [R$]"
      - name: receita_tarifaria_esperada
        description: "Receita tarifária esperada com base na quilometragem [R$]"
      - name: subsidio_esperado
        description: "Subsídio esperado com base na quilometragem [R$]"
      - name: subsidio_glosado
        description: "Subsídio glosado conforme os decretos e resoluções vigentes [R$]"
      - name: receita_total_aferida
        description: "Receita total aferida (receita tarifária + subsidio pago) [R$]"
      - name: receita_tarifaria_aferida
        description: "Receita tarifária aferida com base no RDO informado pelos consórcios [R$]"
      - name: subsidio_pago
        description: "Subsídio pago [R$]"
      - name: saldo
        description: "Saldo entre a receita esperada e aferida, descontado o subsídio glosado [R$]"
  - name: balanco_servico_quinzena
    description: "Balanço da receita aferida e esperada por serviço e
    quinzena para serviços-dia subsidiados. Ver metodologia em NOTA TÉCNICA TR/SUBTT Nº 01/2024"
    columns:
      - name: quinzena
        description: "Quinzena"
      - name: data_inicial_quinzena
        description: "Data inicial da quinzena"
      - name: data_final_quinzena
        description: "Data final da quinzena"
      - name: servico
        description: "Serviço"
      - name: km_subsidiada
        description: "Quilometragem apurada e subsidiada via algoritmo [km]"
      - name: receita_total_esperada
        description: "Receita total esperada com base na quilometragem (IRK x km) [R$]"
      - name: receita_tarifaria_esperada
        description: "Receita tarifária esperada com base na quilometragem [R$]"
      - name: subsidio_esperado
        description: "Subsídio esperado com base na quilometragem [R$]"
      - name: subsidio_glosado
        description: "Subsídio glosado conforme os decretos e resoluções vigentes [R$]"
      - name: receita_total_aferida
        description: "Receita total aferida (receita tarifária + subsidio pago) [R$]"
      - name: receita_tarifaria_aferida
        description: "Receita tarifária aferida com base no RDO informado pelos consórcios [R$]"
      - name: subsidio_pago
        description: "Subsídio pago [R$]"
      - name: saldo
        description: "Saldo entre a receita esperada e aferida,
        descontado o subsídio glosado [R$]"
  - name: parametros_km
    description: "Parâmetros de remuneração do subsídio dos serviços de ônibus (SPPO) por tipo de viagem"
    columns:
      - name: indicador_licenciado
        description: "Indicador se o veículo encontra-se licenciado"
      - name: indicador_ar_condicionado
        description: "Indicador se o veículo foi licenciado com ar condicionado"
      - name: indicador_autuacao_ar_condicionado
        description: "Indicador se o veículo foi autuado por inoperância ou mau funcionamento do sistema de ar condicionado"
      - name: indicador_autuacao_seguranca
        description: "Indicador se o veículo foi autuado por infração relacionada à segurança do veículo"
      - name: indicador_autuacao_limpeza
        description: "Indicador se o veículo foi autuado por infração relacionada à limpeza do veículo"
      - name: indicador_autuacao_equipamento
        description: "Indicador se o veículo foi autuado por infração relacionada à inoperância ou mau funcionamento de equipamentos do veículo"
      - name: indicador_sensor_temperatura
        description: "Indicador se o sensor de temperatura do veículo não estava em funcionamento conforme especificação da SMTR"
      - name: indicador_validador_sbd
        description: "Indicador se o veículo se encontra com o novo validador do Sistema de Bilhetagem Digital (SBD) instalado"
      - name: status
        description: "Classificação, observados os demais parâmetros para remuneração"
      - name: subsidio_km
        description: "Valor de subsídio de remuneração (R$/km)"
      - name: irk
        description: "Índice de Remuneração por km (R$/km)"
      - name: data_inicio
        description: "Data inicial do período de vigência dos demais atributos"
      - name: data_fim
        description: "Data final do período de vigência dos demais atributos"
      - name: legislacao
        description: "Legislação que estabelece o valor e regras de remuneração"
      - name: ordem
        description: "Ordem de prioridade de aplicação dos valores de remuneração"
  - name: receita_tarifaria_servico_nao_identificado_quinzena
    description: "Receita tarifária proveniente do RDO para serviços de ônibus
    dos consórcios que não foram identificados nos planos operacionais dos respectivos dias."
    columns:
      - name: quinzena
        description: "Quinzena"
      - name: data_inicial_quinzena
        description: "Data inicial da quinzena"
      - name: data_final_quinzena
        description: "Data final da quinzena"
      - name: servico_tratado_rdo
        description: "Serviço tratado com base no campo linha do RDO,
        utilizado para cruzamento com o plano operacional."
      - name: linha_rdo
        description: "Linha conforme RDO"
      - name: tipo_servico_rdo
        description: "Tipo do serviço conforme RDO"
      - name: ordem_servico_rdo
        description: "Ordem do serviço conforme o RDO"
      - name: quantidade_dias_rdo
        description: "Quantidade de dias em que o serviço foi encontrado
        no RDO na respectiva quinzena"
      - name: receita_tarifaria_aferida_rdo
        description: "Receita tarifária aferida com base no RDO"
