version: 2

models:
  # - name: data_versao_efetiva
  #   description: "Especifica qual data versao mais recente disponível para uma determinada data."
  #   columns:
  #     - name: data
  #       description: "The primary key for this table"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_agency
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_calendar
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_frota_determinada
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_holidays
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_linhas
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_routes
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_shapes
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_stop_details
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_stop_times
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_stops
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  #     - name: data_versao_efetiva_trips
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null:
  #             partition_column: data
  - name: routes_desaninhada
    description: Cadastro dos serviços (routes)
    columns:
      - name: route_id
        tests:
          - not_null:
              partition_column: data_versao
          - unique_key:
              partition_column: data_versao
              combined_keys: ""
  - name: trips_desaninhada
    description: Cadastro de itinerários (trips)
    columns:
      - name: trip_id
        description: Identificador único para um itinerário
        tests:
          - not_null:
              partition_column: data_versao
          - unique_key:
              partition_column: data_versao
              combined_keys: ""
          - one_to_one:
              partition_column: data_versao
              to_table: ref('shapes_geom')
      - name: route_id
        description: Identificador única para a route (serviço)
        tests:
          - many_to_one:
              foreign_key: route_id
              partition_column: data_versao
              to_table: ref('routes_desaninhada')
  - name: shapes_geom
    description: tabela com as linestrings de cada itinarário consolidadas a partir da captura ponto a ponto
    columns:
      - name: shape_id
        tests:
          - not_null:
              partition_column: data_versao
      - name: trip_id
        tests:
          - not_null:
              partition_column: data_versao
          - unique_key:
              partition_column: data_versao
              combined_keys: ""
          - one_to_one:
              partition_column: data_versao
              to_table: ref('trips_desaninhada')
