version: 2

models:
  - name: tg_transacao
    description: "Microdados das transações de cartão. Cada registro é uma transação."
    columns:
      - name: data
        description: "Data da transação (partição)"
      - name: id_empresa
        description: "Código da empresa que opera o veículo de origem da transação"
      - name: id_veiculo
        description: "Número do veículo configurado no equipamento (apenas número)"
      - name: id_cartao
        description: "Número único criptografado do cartão RioCard"
      - name: id_tipo_cartao
        description: "Número do aplicação, indica qual o tipo do cartão (ex: gratuidade, vale transporte). Categorias podem ser encontradas na tabela dicionário."
      - name: sequencial_transacao_cartao
        description: "Número sequencial histórico de transações do cartão"
      - name: timestamp_transacao
        description: "Timestamp da transação em GMT-3"
      - name: tipo_embarque
        description: "Tipo de embarque atual, indica se é integração ou não"
      - name: tipo_debito
        description: "Tipo de débito no cartão, indica o tipo de tarifa executada (ex: cheia, com desconto). Categorias podem ser encontradas na tabela dicionário."
      - name: mensagem_debito
        description: "Mensagem de estado do débito no cartão. Categorias podem ser encontradas na tabela dicionário."
      - name: valor_tarifa
        description: "Valor da tarifa configurado no equipamento (R$)"
      - name: valor_tarifa_anterior
        description: "Valor da tarifa anterior da viagem anterior (R$)"
      - name: valor_debitado
        description: "Valor debitado na viagem atual (R$)"
      - name: valor_promo_desconto
        description: "Valor promocional ou de desconto da tarifa (R$)"
      - name: valor_total_integracao
        description: "Soma do valor total pago em uma integração (R$)"     
  - name: tg_dicionario
    description: "Dicionário de dados"
    columns:
      - name: chave
        description: "Chave"
      - name: cobertura_temporal
        description: "Cobertura temporal"
      - name: id_tabela
        description: "Nome da tabela"
      - name: nome_coluna
        description: "Nome da coluna"
      - name: valor
        description: "Valor"