version: 2
sources:
  - name: "br_rj_riodejaneiro_gtfs"

models:
  - name: agency_gtfs
    description: "Agência de transporte público com serviços representados neste conjunto de dados."
    columns:
      - name: agency_id
        description:  "Identifica uma marca de transporte público que geralmente é sinônimo de agência de transporte público."
      - name: agency_name
        description: "Nome completo da agência de transporte público."
      - name: agency_url
        description: "URL da agência de transporte público."
      - name: agency_timezone
        description: "Fuso horário onde a agência de transporte público está localizada"
      - name: agency_lang
        description: "Idioma principal usado por esta agência de transporte público."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: calendar_gtfs
    description: "Datas de serviço especificadas usando uma programação semanal com datas de início e término."
    columns:
      - name: service_id
        description: "Identifica um conjunto de datas em que o serviço está disponível para uma ou mais rotas."
      - name: monday
        description: "Indica se o serviço funciona todas as segundas-feiras no intervalo de datas especificado pelos campos start_date e end_date"
      - name: tuesday
        description: "Funciona da mesma forma que segunda-feira, exceto se aplica às terças-feiras."
      - name: wednesday
        description: "Funciona da mesma forma que segunda-feira, exceto se aplica às quartas-feiras."
      - name: thursday
        description: "Funciona da mesma forma que segunda-feira, exceto se aplica às quintas-feiras."
      - name: friday
        description: "Funciona da mesma forma que segunda-feira, exceto se aplica às sextas-feiras."
      - name: saturday
        description: "Funciona da mesma forma que segunda-feira, exceto se aplica aos sábados."
      - name: sunday
        description: "Funciona da mesma forma que segunda-feira, exceto se aplica aos domingos."
      - name: start_date
        description: "Inicie o dia de serviço para o intervalo de serviço."
      - name: end_date
        description: "Finalize o dia de serviço para o intervalo de serviço."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: calendar_dates_gtfs
    description: "Exceções para os serviços definidos no calendar.txt."
    columns:
      - name: service_id
        description: "Identifica um conjunto de datas quando ocorre uma exceção de serviço para uma ou mais rotas"
      - name: date
        description: "Data em que ocorre a exceção de serviço."
      - name: exception_type
        description: "Indica se o serviço está disponível na data especificada no campo de data."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: fare_attributes_gtfs
    description: "Informações sobre tarifas para rotas de uma agência de transporte público."
    columns:
      - name: fare_id
        description: "Identifica uma classe de tarifa."
      - name: price
        description: "Preço da tarifa, na unidade especificada por currency_type."
      - name: currency_type
        description: "Moeda usada para pagar a tarifa."
      - name: payment_method
        description: "Indica quando a tarifa deve ser paga."
      - name: transfers
        description: "Indica o número de transferências permitidas nesta tarifa"
      - name: agency_id
        description: "Identifica a agência relevante para uma tarifa."
      - name: transfer_duration
        description: "Período de tempo em segundos antes que uma transferência expire."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: fare_rules_gtfs
    description: "Regras para aplicação de tarifas de itinerários."
    columns:
      - name: fare_id
        description: "Identifica uma classe de tarifa."
      - name: route_id
        description: "Identifica uma rota associada à classe de tarifa."
      - name: origin_id
        description: "Identifica uma zona de origem."
      - name: destination_id
        description: "Identifica uma zona de destino."
      - name: contains_id
        description: "Identifica as zonas nas quais um passageiro entrará ao usar uma determinada classe de tarifa."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: feed_info_gtfs
    description: "Metadados do conjunto de dados, incluindo informações sobre editor, versão e expiração."
    columns:
      - name: feed_publisher_name
        description: "Nome completo da organização que publica o conjunto de dados."
      - name: feed_publisher_url
        description: "URL do site da organização que publica o conjunto de dados."
      - name: feed_lang
        description: "Idioma padrão usado para o texto neste conjunto de dados."
      - name: default_lang
        description: "Define o idioma que deve ser usado quando o consumidor de dados não conhece o idioma do passageiro."
      - name: feed_start_date
        description: "O conjunto de dados fornece informações de programação completas e confiáveis ​​para serviço no período que vai do início do dia feed_start_date até o final do dia feed_end_date."
      - name: feed_end_date
        description: "O conjunto de dados fornece informações de programação completas e confiáveis ​​para serviço no período que vai do início do dia feed_start_date até o final do dia feed_end_date."
      - name: feed_version
        description: "String que indica a versão atual do conjunto de dados GTFS."
      - name: feed_contact_email
        description: "Endereço de e-mail para comunicação sobre o conjunto de dados GTFS e práticas de publicação de dados."
      - name: feed_contact_url
        description: "n, um formulário web, suporte técnico ou outras ferramentas para comunicação sobre o conjunto de dados GTFS e práticas de publicação de dados."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: frequencies_gtfs
    description: "Intervalo (tempo entre viagens) para serviço baseado em intervalo ou uma representação compactada de serviço com horário fixo."
    columns:
      - name: trip_id
        description: "Identifica uma viagem à qual se aplica o intervalo de serviço especificado."
      - name: start_time
        description: "Hora em que o primeiro veículo sai da primeira parada da viagem com o intervalo especificado."
      - name: end_time
        description: "Hora em que o serviço muda para um intervalo diferente (ou cessa) na primeira parada da viagem."
      - name: headway_secs
        description: "Tempo, em segundos, entre partidas da mesma parada (intervalo) da viagem, durante o intervalo de tempo especificado por start_time e end_time."
      - name: exact_times
        description: "Indica o tipo de serviço para uma viagem."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: routes_gtfs
    description: "Rotas de trânsito. Uma rota é um grupo de viagens exibidas aos passageiros como um único serviço."
    columns:
      - name: route_id
        description: "Identifica uma rota."
      - name: agency_id
        description: "Agência para a rota especificada."
      - name: route_short_name
        description: "Nome abreviado de uma rota."
      - name: route_long_name
        description: "Nome completo de uma rota."
      - name: route_desc
        description: "Descrição de uma rota que fornece informações úteis e de qualidade."
      - name: route_type
        description: "Indica o tipo de transporte utilizado em uma rota."
      - name: route_url
        description: "URL de uma página da web sobre uma rota específica." 
      - name: route_color
        description: "Designação de cores da rota que corresponda ao material voltado para o público."
      - name: route_text_color
        description: "Cor legível a ser usada para texto desenhado contra um fundo de route_color."
      - name: route_sort_order
        description: "Ordena as rotas de forma ideal para apresentação aos clientes."
      - name: continuous_pickup
        description: "Indica que o passageiro pode embarcar no veículo de transporte público em qualquer ponto ao longo do trajeto de viagem do veículo, conforme descrito em shape.txt, em cada viagem do trajeto."
      - name: continuous_drop_off
        description: "Indica que o passageiro pode descer do veículo de transporte público em qualquer ponto ao longo do trajeto de viagem do veículo, conforme descrito em shape.txt, em cada viagem da rota."
      - name: network_id
        description: "Identifica um grupo de rotas. Várias linhas em rotas.txt podem ter o mesmo network_id."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: shapes_geom_gtfs
    description: "Tabela com os shapes dos serviços."
    columns:
      - name: shape_id
        description: "Identifica uma forma."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: shape
        description: "Dado geográfico construído com a query."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: shapes_gtfs
    description: "Regras para mapear caminhos de deslocamento de veículos, às vezes chamados de alinhamentos de rotas."
    columns:
      - name: shape_id
        description: "Identifica uma forma."
      - name: shape_pt_sequence
        description: "Sequência na qual os pontos da forma se conectam para formar a forma."
      - name: shape_pt_lat
        description: "Latitude de um ponto de forma."
      - name: shape_pt_lon
        description: "Longitude de um ponto de forma."
      - name: shape_dist_traveled
        description: "Distância real percorrida ao longo da forma desde o primeiro ponto da forma até o ponto especificado neste registro."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: stops_gtfs
    description: "Paradas onde os veículos pegam ou deixam os passageiros. Também define estações e entradas de estação."
    columns:
      - name: stop_id
        description: "Identifica uma localização: paragem/plataforma, estação, entrada/saída, nó genérico ou área de embarque"
      - name: stop_code
        description: "Texto curto ou um número que identifica a localização dos passageiros."
      - name: stop_name
        description: "Nome do local."
      - name: tts_stop_name
        description: "Versão legível do stop_name."
      - name: stop_desc
        description: "Descrição do local que fornece informações úteis e de qualidade."
      - name: stop_lat
        description: "Latitude do local."
      - name: stop_lon
        description: "Longitude do local."
      - name: zone_id
        description: "Identifica a zona tarifária para uma parada."
      - name: stop_url
        description: "URL de uma página da web sobre o local."
      - name: location_type
        description: "Tipo de localização."
      - name: parent_station
        description: "Define a hierarquia entre os diferentes locais definidos em stops.txt."
      - name: stop_timezone
        description: "Fuso horário do local."
      - name: wheelchair_boarding
        description: "Indica se o embarque para cadeiras de rodas é possível no local."
      - name: level_id
        description: "Nível do local."
      - name: platform_code
        description: "Identificador de plataforma para uma parada de plataforma (uma parada pertencente a uma estação)."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: stop_times_gtfs
    description: "Horários em que um veículo chega e sai das paradas de cada viagem."
    columns:
      - name: trip_id
        description: "Identifica uma viagem."
      - name: stop_sequence
        description: "Ordem das paradas para uma viagem específica."
      - name: stop_id
        description: "Identifica a parada atendida."
      - name: arrival_time
        description: "Hora de chegada na parada (definida por stop_times.stop_id) para uma viagem específica (definida por stop_times.trip_id) no fuso horário especificado por agency.agency_timezone, não por stops.stop_timezone."
      - name: departure_time
        description: "Hora de partida da parada (definida por stop_times.stop_id) para uma viagem específica (definida por stop_times.trip_id) no fuso horário especificado por agency.agency_timezone, não por stops.stop_timezone."
      - name: stop_headsign
        description: "Texto que aparece na sinalização identificando o destino da viagem aos passageiros."
      - name: pickup_type
        description: "Indica o método de coleta."
      - name: drop_off_type
        description: " Indica o método de entrega."
      - name: continuous_pickup
        description: "Indica que o passageiro pode embarcar no veículo de transporte público em qualquer ponto ao longo do trajeto de viagem do veículo, conforme descrito em shape.txt, deste stop_time até o próximo stop_time na stop_sequence da viagem."
      - name: continuous_drop_off
        description: "Indica que o passageiro pode descer do veículo de transporte público em qualquer ponto ao longo do caminho de viagem do veículo, conforme descrito por shape.txt, deste stop_time até o próximo stop_time na stop_sequence da viagem."
      - name: shape_dist_traveled
        description: "Distância real percorrida ao longo do formato associado, desde a primeira parada até a parada especificada neste registro."
      - name: timepoint
        description: "Indica se os horários de chegada e saída de uma parada são rigorosamente respeitados pelo veículo ou se são horários aproximados e/ou interpolados."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: trips_gtfs
    description: "Viagens para cada rota."
    columns:
      - name: trip_id
        description: "Identifica uma viagem."
      - name: route_id
        description: "Identifica uma rota."
      - name: service_id
        description: "Identifica um conjunto de datas em que o serviço está disponível para uma ou mais rotas."
      - name: trip_headsign
        description: "Texto que aparece na sinalização identificando o destino da viagem aos passageiros."
      - name: trip_short_name
        description: "Texto voltado ao público usado para identificar a viagem aos passageiros, por exemplo, para identificar os números dos trens para viagens de trens suburbanos."
      - name: direction_id
        description: "Indica a direção de deslocamento de uma viagem."
      - name: block_id
        description: "Identifica o bloco ao qual pertence a viagem."
      - name: shape_id
        description: "Identifica uma forma geoespacial que descreve o caminho de deslocamento do veículo para uma viagem."
      - name: wheelchair_accessible
        description: "Indica acessibilidade para cadeiras de rodas."
      - name: bikes_allowed
        description: "Indica se bicicletas são permitidas."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."

  - name: ordem_servico_gtfs
    description: "Dados das linhas presentes no município."
    columns:
      - name: servico
        description: "Número da linha de ônibus."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: vista
        description: "Letreiro do ônibus."
      - name: consorcio
        description: "Nome do consórcio responsável pela linha."
      - name: horario_inicio
        description: "Horário inicial de funcionamento."
      - name: horario_fim
        description: "Horário da última viagem."
      - name: extensao_ida
        description: "Distância percorrida na ida."
      - name: extensao_volta
        description: "Distância percorrida na volta."
      - name: partidas_ida
        description: "Quantidade de partidas no sentido ida."
      - name: partidas_volta
        description: "Quantidade de partidas no sentido volta."
      - name: viagens_planejadas
        description: "Quantidade de viagens realizadas."
      - name: distancia_total_planejada
        description: "Distância total planejada diária para o serviço. "
      - name: tipo_dia
        description: "Tipo de dia, se dia útil, sábado, domingo ou ponto facultativo."
      - name: data_versao
        description: "Data de referência do feed (versão)."
      - name: timestamp_captura
        description: "Carimbo de data e hora da captura."
      - name: versao_modelo 
        description: "Código de controle de versão (SHA do GitHub)."