version: 2

models:
  - name: transacao
    description: "Tabela de transações"
    columns:
      - name: data
        description: "Data da transação (partição)"
      - name: hora
        description: "Hora da transação"
      - name: datetime_transacao
        description: "Data e hora da transação em GMT-3 (formato YYYY-MM-ddTHH:mm:ss.ssssss)"
      - name: datetime_processamento
        description: "Data e hora de processamento da transação em GMT-3 (formato YYYY-MM-ddTHH:mm:ss.ssssss)"
      - name: datetime_captura
        description: "Timestamp de captura em GMT-3 (formato YYYY-MM-dd HH:mm:ssTZD)"
      - name: modo
        description: "Tipo de transporte (Ônibus, Van, BRT)"
      - name: id_consorcio
        description: "Identificador do consórcio na tabela cadastro.consorcios"
      - name: consorcio
        description: "Nome do consórcio"
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
      - name: operadora
        description: "Nome da operadora de transporte (mascarado se for pessoa física)"
      - name: servico
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...)"
      - name: sentido
        description: "Sentido de operação do serviço (0 = ida, 1 = volta)"
      - name: id_veiculo
        description: "Identificador único do veículo"
      - name: id_cliente
        description: "Identificador único do cliente"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1168584191451386864'
      - name: id_transacao
        description: "Identificador único da transação"
      - name: id_tipo_pagamento
        description: "Código do tipo de pagamento utilizado"
      - name: tipo_transacao
        description: "Tipo de transação realizada (a primeira perna de integrações são classificadas como tipo Débito e não Integração)"
      # - name: indicador_integracao
      #   description: "Indicador booleano se a transação é parte de uma integração (coluna atualizada diariamente)"
      - name: id_tipo_integracao
        description: "Tipo da integração realizada (identificador relacionado à matriz de integração)"
      - name: id_integracao
        description: "Identificador único da integração"
      - name: latitude
        description: "Latitude da transação (WGS84)"
      - name: longitude
        description: "Longitude da transação (WGS84)"
      - name: stop_id
        description: "Código identificador do ponto de embarque (GTFS)"
      - name: stop_lat
        description: "Latitude do ponto de embarque (GTFS)"
      - name: stop_lon
        description: "Longitude do ponto de embarque (GTFS)"
      - name: valor_transacao
        description: "Valor debitado na transação atual (R$)"
      - name: versao
        description: "Código de controle de versão do dado (SHA Github)"
  - name: ordem_pagamento
    description: "Tabela de ordem de pagamento do banco de dados de dados da Jaé"
    columns:
      - name: data_ordem
        description: "Data da ordem de pagamento (partição)"
      - name: data_pagamento
        description: "Data de pagamento da ordem"
      - name: id_consorcio
        description: "Identificador do consórcio na tabela cadastro.consorcios"
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
      - name: servico
        description: "Nome curto da linha operada com variação de serviço (ex: 010, 011SN, ...)"
      - name: id_ordem_pagamento
        description: "Identificador da ordem pagamento no banco de dados da Jaé"
      - name: id_ordem_ressarcimento
        description: "Identificador da ordem ressarcimento no banco de dados da Jaé"
      - name: quantidade_transacao_debito
        description: "Quantidade de transações feitas na modalidade débito"
      - name: valor_debito
        description: "Valor total das transações feitas na modalidade débito (R$)"
      - name: quantidade_transacao_especie
        description: "Quantidade de transações feitas em espécie"
      - name: valor_especie
        description: "Valor total das transações feitas em espécie (R$)"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de transações feitas com gratuidade"
      - name: valor_gratuidade
        description: "Valor total das transações feitas com gratuidade (R$)"
      - name: quantidade_transacao_integracao
        description: "Quantidade de transações feitas com integração"
      - name: valor_integracao
        description: "Valor total das transações feitas com integração (R$)"
      - name: quantidade_transacao_rateio_credito
        description: ""
      - name: valor_rateio_credito
        description: ""
      - name: quantidade_transacao_rateio_debito
        description: ""
      - name: valor_rateio_debito
        description: ""
      - name: quantidade_total_transacao
        description: "Quantidade total de transações realizadas"
      - name: valor_total_transacao_bruto
        description: "Valor total das transações realizadas (R$)"
      - name: valor_desconto_taxa
        description: "Valor da taxa descontado do valor total (R$)"
      - name: valor_total_transacao_liquido
        description: "Valor total das transações menos o valor_desconto_taxa (R$)"
      - name: quantidade_total_transacao_captura
        description: "Quantidade total de transações calculada pela captura de transações"
      - name: valor_total_transacao_captura
        description: "Valor total das transações realizadas calculada pela captura de transações (R$)"
      - name: indicador_ordem_valida
        description: "Indicador de validação da ordem de pagamento i.e. se a quantidade e valor total informados são encontrados na captura de transações individuais"
      - name: versao
        description: "Código de controle de versão do dado (SHA Github)"
  - name: integracao
    description: "Tabela com a relação de integrações entre transações [Dados em fase de teste]"
    columns:
      - name: data
        description: "Data da transação (partição)"
      - name: hora
        description: "Hora da transação"
      - name: datetime_processamento_integracao
        description: "Data e hora de processamento da integração em GMT-3"
      - name: datetime_captura
        description: "Data e hora da captura da integração em GMT-3"
      - name: datetime_transacao
        description: "Data e hora da transação em GMT-3"
      - name: id_integracao
        description: "Identificador único da integração"
      - name: sequencia_integracao
        description: "Sequência da transação dentro da integração"
      - name: id_integracao_sequencia
        description: "Identificador único da integração + sequência"
      - name: modo
        description: "Tipo de transporte (Ônibus, Van, BRT)"
      - name: id_consorcio
        description: "Identificador do consórcio na tabela cadastro.consorcios"
      - name: consorcio
        description: "Nome do consórcio"
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
      - name: operadora
        description: "Nome da operadora de transporte (mascarado se for pessoa física)"
      - name: servico
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...)"
      - name: id_transacao
        description: "Identificador único da transação"
      - name: sentido
        description: "Sentido de operação do serviço (0 = ida, 1 = volta)"
      - name: percentual_rateio
        description: "Percentual de rateio do valor total para a operadora"
      - name: valor_rateio_compensacao
        description: "Valor a ser compensado pela ou à operadora (R$)"
      - name: valor_rateio
        description: "Valor real ganho pela operadora pela transação (R$)"
      - name: valor_transacao
        description: "Valor debitado do cartão no momento da transação (R$)"
      - name: valor_transacao_total
        description: "Valor total das transações da integração (R$)"
      - name: texto_adicional
        description: "Observação adicional"
      - name: versao
        description: "Código de controle de versão do dado (SHA Github)"
  - name: matriz_integracao
    description: "matriz integracao"
    columns:
      - name: id_matriz_integracao
        description: "Identificador único da integração"
      - name: sequencia_integracao
        description: "Sequencia da transação dentro da integração"
      - name: modo
        description: "Tipo de transporte (Ônibus, Van, BRT)"
      - name: percentual_rateio
        description: "Percentual de rateio do valor total para a operadora"
      - name: data_inicio_validade
        description: "Data de início da validade da matriz"
      - name: data_fim_validade
        description: "Data de fim da validade da matriz"
      - name: versao
        description: "Código de controle de versão do dado (SHA Github)"
  - name: gps_validador
    description: "Tabela com os dados dos sinais de GPS enviados pelos validadores da Jaé"
    columns:
      - name: modo
        description: "Tipo de transporte (Ônibus, Van, BRT)"
      - name: data
        description: "Data do recebimento da transmissão do GPS (partição)"
      - name: hora
        description: "Hora do recebimento da transmissão do GPS"
      - name: datetime_gps
        description: "Data e hora do recebimento da transmissão do GPS em GMT-3"
      - name: datetime_captura
        description: "Data e hora da captura do dado de GPS em GMT-3"
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
      - name: operadora
        description: "Nome da operadora de transporte (mascarado se for pessoa física)"
      - name: servico
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...)"
      - name: id_validador
        description: "Número de série do validador"
      - name: id_transmissao_gps
        description: "Identificador único da tabela de GPS dos validadores"
      - name: latitude
        description: "Latitude do validador no momento da transmissão"
      - name: longitude
        description: "Longitude do validador no momento da transmissão"
      - name: id_veiculo
        description: "[EM DESENVOLVIMENTO] Código identificador do veículo (número de ordem)"
      - name: sentido
        description: "Sentido da linha"
      - name: estado_equipamento
        description: "Validador aberto ou fechado no momento da transmissão"
      - name: temperatura
        description: "Temperatura do local, medida pelo sensor do validador (ºC)"
      - name: versao
        description: "Código de controle de versão do dado (SHA Github)"
  - name: dicionario
    description: "Dicionário de dados"
    columns:
      - name: chave
        description: "Chave"
      - name: cobertura_temporal
        description: "Cobertura temporal"
      - name: id_tabela
        description: "Nome da tabela"
      - name: coluna
        description: "Nome da coluna"
      - name: valor
        description: "Valor"
        
