version: 2

models:
  - name: integracao_invalida
    description: "Tabela para validação dos dados de integração da Jaé"
    columns:
      - name: data
        description: "Data de processamento da integração (partição)"
      - name: id_integracao
        description: "Identificador único da integração"
      - name: modos
        description: "Sequência modos das transações presentes na integração (separado por ', ')"
      - name: indicador_fora_matriz
        description: "Indica se a sequência de modos não aparece na tabela br_rj_riodejaneiro_bilhetagem.matriz_integracao"
      - name: tipo_tempo_invalido
        description: "Indica se a integração durou mais que 3 horas ou se houve transações com tempo menor que 5 minutos entre elas"
      - name: versao
        description: "Código de controle de versão do dado (SHA Github)" 
  - name: transacao_invalida
    description: "Tabela para validação dos dados de transação da Jaé"
    columns:
      - name: data
        description: "Data da transação (partição)"
      - name: hora
        description: "Hora da transação"
      - name: datetime_transacao
        description: "Data e hora da transação"
      - name: datetime_processamento
        description: "Data e hora de processamento da transação"
      - name: datetime_captura
        description: "Data e hora de captura dos dados da transação"
      - name: modo
        description: "Tipo de transporte (Ônibus, Van, BRT)"
      - name: id_consorcio
        description: "dentificador do consórcio na tabela cadastro.consorcios"
      - name: consorcio
        description: "Nome do consórcio"
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
      - name: operadora
        description: "Nome da operadora de transporte (mascarado se for pessoa física)"
      - name: id_servico_jae
        description: "Identificador da linha no banco de dados da jaé (É possível cruzar os dados com a tabela rj-smtr.cadastro.servicos usando a coluna id_servico_jae)"
      - name: servico
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação no caso de BRT"
      - name: descricao_servico
        description: "Nome completo da linha ou estação"
      - name: id_transacao
        description: "Identificador único da transação"
      - name: longitude
        description: "Longitude da transação (WGS84)"
      - name: latitude
        description: "Latitude da transação (WGS84)"
      - name: longitude_servico
        description: "Longitude do stop no GTFS (WGS84)"
      - name: latitude_servico
        description: "Latitude do stop no GTFS (WGS84)"
      - name: tipo_transacao_invalida
        description: "Indica se a transação está com geolocalização zerada, fora do município ou fora da estação indicada (BRT)"
      - name: indicador_servico_gtfs
        description: "Indica se o serviço tem correspondência com as tabela 'trips' ou 'stops' do GTFS"
      - name: versao
        description: "Código de controle de versão do dado (SHA Github)"
        