# Definição de taxa de atualização
scheduling:
  cron: "*/5 * * * *"
# Parâmetros de backfill
backfill:
  # Formato %Y-%m-%d %H:%M:%S
  start_timestamp: "2021-11-24 00:00:00"
  interval:
    days: 30

  # Definição de particionamento
# - column: nome da coluna
# - type: deve ser um dos seguintes
#   * DATE (não exige período)
#   * DATE_TRUNC (exige período MONTH/YEAR)
#   * DATETIME_TRUNC (exige período DAY/HOUR/MONTH/YEAR)
#   * TIMESTAMP_TRUNC (exige período DAY/HOUR/MONTH/YEAR)
#   * <To-do> RANGE_BUCKET
#   * <To-do> GENERATE_ARRAY
# - period: período (conforme especificado acima)
partitioning:
  column: "data"
  type: ""
  period: ""

# Parâmetros da query
parameters:
  # IdModalSMTR
  # 20 -> BRT
  id_modal_smtr: ["'20'", "'B'"]

  # Filtro de velocidade no cálculo de viagens realizadas
  ## Serão consideradas somente velocidades entre os valores abaixo
  filtro_min_velocidade: 10 # viagens_realizadas
  filtro_max_velocidade: 90 # viagens_realizadas

  # Parametros de intersecção do ônibus com rota
  ## Tamanho do buffer da rota
  tamanho_buffer_metros: 100 # aux_registros_intersec /flag_trajeto_correto

  ## Tamanho do buffer em torno dos pontos inciais e finais em aux_registros_intersec
  buffer_inicio_fim_metros: 250

  ## Intervalo máximo que um veículo pode ficar fora da rota para ser considerado
  ## dentro da rota. Afeta a flag flag_trajeto_correto_hist
  intervalo_max_desvio_segundos: 600 # flag_trajeto_correto

  ## Intervalo mínimo de detecção de saída de viagem
  faixa_horaria_minutos: 5 # aux_registros_intersec
  ## Tamanho da janela de tempo (em segundos) para cálculo da média móvel de velocidade do veículo
  janela_movel_velocidade: 600 # aux_registros_velocidade
  ## velocidade máxima média que o veículo pode atingir para evitar outliers provenientes de túneis
  velocidade_maxima: 60
  ## Velocidade mínima para que o carro seja considerado em movimento em aux_registros_velocidade
  velocidade_limiar_parado: 3
  ## Distância mínima para que o veículo seja identificado parado em um terminal ou garagem em aux_registros_parada
  distancia_limiar_parada: 250

  # dependências de views/tabelas
  registros_nested: rj-smtr.br_rj_riodejaneiro_brt_gps.registros
  registros: "rj-smtr.br_rj_riodejaneiro_brt_gps.registros_desaninhada" # registros_filtrada
  limites_caixa: "rj-smtr.br_rj_riodejaneiro_geo.limites_geograficos_caixa" # registros_filtrada
  registros_filtrada: "rj-smtr.br_rj_riodejaneiro_brt_gps.aux_registros_filtrada" # aux_registros_*
  terminais: "rj-smtr.br_rj_riodejaneiro_transporte.estacoes_e_terminais_brt" # aux_registros_parada
  polygon_garagem: "rj-smtr.br_rj_riodejaneiro_geo.garagens_polygon" # aux_registros_parada
  shapes: "rj-smtr.br_rj_riodejaneiro_sigmob.shapes_geom" # aux_registros_flag_trajeto_correto, aux_registros_intersec
  data_versao_efetiva: "rj-smtr.br_rj_riodejaneiro_sigmob.data_versao_efetiva" # aux_registros_flag_trajeto_correto, aux_registros_intersec
  intersec: "rj-smtr.br_rj_riodejaneiro_brt_gps.aux_registros_intersec" # viagens_realizadas

# Lista de views do dataset
# Atributos de cada view:
# - name: nome sem terminação .sql ou .yaml
# - materialized: true|false para materializar ou não
# - depends_on: lista de views das quais ela depende
views:
  registros_desaninhada:
    materialized: false
    depends_on: []

  aux_registros_filtrada:
    materialized: true
    depends_on:
      - br_rj_riodejaneiro_geo.limites_geograficos_caixa
      - br_rj_riodejaneiro_brt_gps.registros

  aux_registros_velocidade:
    materialized: false
    depends_on:
      - br_rj_riodejaneiro_brt_gps.aux_registros_filtrada

  aux_registros_parada:
    materialized: false
    depends_on:
      - br_rj_riodejaneiro_transporte.estacoes_e_terminais_brt
      - br_rj_riodejaneiro_geo.garagens_polygon
      - br_rj_riodejaneiro_brt_gps.aux_registros_filtrada

  aux_registros_flag_trajeto_correto:
    materialized: false
    depends_on:
      - br_rj_riodejaneiro_brt_gps.aux_registros_filtrada
      # - br_rj_riodejaneiro_sigmob.shapes_geom
      # - br_rj_riodejaneiro_sigmob.data_versao_efetiva

  aux_registros_intersec:
    materialized: false
    depends_on:
      - br_rj_riodejaneiro_sigmob.shapes_geom
      # - br_rj_riodejaneiro_sigmob.data_versao_efetiva
      # - br_rj_riodejaneiro_brt_gps._aux_registros_filtrada

  viagens_realizadas:
    materialized: false
    depends_on:
      - br_rj_riodejaneiro_brt_gps.aux_registros_intersec
