version: 2
sources:
  - name: "br_rj_riodejaneiro_recurso"

models:
  - name: recurso_sppo
    description: "Recursos abertos na plataforma MoviDesk para pagamento de subsídio de viagens individuais de ônibus"
    columns:
     - name: data_extracao
       description: "Data de extração dos dados"
     - name: data_recurso
       description:  "Data de criação do ticket para pedido de recurso no Movidesk"
     - name: protocol
       description:  "Número de protocolo do ticket"
     - name: id_ticket
       description:  "Número identificador do ticket"
     - name: servico
       description: "Tipo do serviço de ônibus"
     - name: direcao_servico
       description: "Direção do serviço"
     - name: consorcio
       description:  "Nome do consórcio"
     - name: linha
       description:  "Número da linha"
     - name: numero_ordem_veiculo
       description:  "Número de ordem do veículo (Somente números)"
     - name: dia_viagem
       description:  "Dia da viagem do ticket"
     - name: hora_inicio_viagem
       description: "Horário de início da viagem" 
     - name: hora_fim_viagem
       description: "Horário de fim da viagem" 
     - name: motivo
       description: "Motivo para criação do recurso" 
     - name: julgamento
       description: "Julgamento do recurso"
     - name: motivo_indeferido
       description: "Motivos para indeferimento"
     - name: observacao
       description: "Observações acerca do julgamentodo recurso"


