version: 2
sources:
- name: br_rj_riodejaneiro_recurso
models:
  - name: recurso_sppo
    description: Recursos abertos na plataforma Movidesk para pagamento de subsídio de viagens individuais de ônibus
    columns:
      - name: timestamp_captura
        description: Data e hora de captura dos dados
      - name: data_recurso
        description: Data de criação do ticket para pedido de recurso no Movidesk
      - name: id_recurso
        description: Número de id do recurso
      - name: id_ticket
        description: Número identificador do ticket
      - name: tipo_servico
        description: Tipo do serviço de ônibus
      - name: sentido
        description: Sentido do ônibus
      - name: consorcio
        description: Nome do consórcio
      - name: linha
        description: Número da linha
      - name: id_veiculo
        description: Número de identificação do veículo (Somente números)
      - name: data_viagem
        description: Dia da viagem do recurso
      - name: hora_inicio_viagem
        description: Horário de início da viagem
      - name: hora_fim_viagem
        description: Horário de fim da viagem
      - name: motivo
        description: Motivo para criação do recurso
      - name: julgamento
        description: Julgamento do recurso
      - name: motivo_indeferido
        description: Motivos para indeferimento
      - name: motivo_deferido
        description: Motivos para deferimento
      - name: observacao
        description: Observações acerca do julgamentodo recurso
      - name: versao
        description: Código de controle de versão do dado (SHA Github)
