version: 2
sources:
- name: br_rj_riodejaneiro_recurso
models:
  - name: recurso_sppo
    description: Recursos abertos na plataforma Movidesk para pagamento de subsídio de viagens individuais de ônibus
    columns:
      - name: datetime_captura
        description: Data de captura dos dados
      - name: datetime_recurso
        description: Data de criação do ticket para pedido de recurso no Movidesk
      - name: datetime_update_recurso
        description: Data de atualização do ticket para pedido de recurso no Movidesk
      - name: id_recurso
        description: Número de id do recurso
      - name: servico
        description: Tipo do serviço de ônibus
      - name: sentido
        description: Sentido do ônibus
      - name: consorcio
        description: Nome do consórcio
      - name: id_veiculo
        description: Número de identificação do veículo (Somente números)
      - name: datetime_partida
        description: "Datetime da partida da viagem"
      - name: datetime_chegada
        description: "Datetime da chegada da viagem"
      - name: motivo
        description: Motivo para criação do recurso
      - name: julgamento
        description: Julgamento do recurso
      - name: motivo_julgamento
        description: Motivos para julgamento
      - name: observacao
        description: Observações acerca do julgamentodo recurso
      - name: data
        description: Data do recurso (partição da tabela)
