version: 2

sources:
  - name: br_rj_riodejaneiro_bilhetagem_staging
    database: rj-smtr-staging

    tables:
      - name: transacao
      - name: linha
      - name: dicionario
      - name: consorcio
      - name: operadora_transporte
      - name: ordem_pagamento
      - name: ordem_ressarcimento
      - name: conta_bancaria
      - name: contato_pessoa_juridica
      - name: cliente
      - name: percentual_rateio_integracao
      - name: integracao_transacao
      - name: tipo_modal

  - name: br_rj_riodejaneiro_gtfs_staging
    database: rj-smtr-staging

    tables:
      - name: agency
      - name: calendar
      - name: calendar_dates
      - name: fare_attributes
      - name: fare_rules
      - name: feed_info
      - name: frequencies
      - name: routes
      - name: shapes
      - name: stops
      - name: stop_times
      - name: trips
      - name: ordem_servico

  - name: br_rj_riodejaneiro_stu_staging
    database: rj-smtr-staging
    
    tables:
      - name: operadora_empresa
      - name: operadora_pessoa_fisica

  - name: br_rj_riodejaneiro_recursos_staging
    database: rj-smtr-staging

    tables:
      - name: recursos_sppo_viagens_individuais
