version: 2

sources:
  - name: br_rj_riodejaneiro_bilhetagem_staging
    database: rj-smtr-staging

    tables:
      - name: transacao
      - name: linha
      - name: grupo
      - name: grupo_linha
      - name: dicionario

  - name: br_rj_riodejaneiro_gtfs_staging
    database: rj-smtr-dev

    tables:
      - name: agency
      - name: calendar
      - name: calendar_dates
      - name: fare_attributes
      - name: fare_rules
      - name: feed_info
      - name: frequencies
      - name: routes
      - name: shapes
      - name: stops
      - name: stop_times
      - name: trips
      - name: quadro