version: 2

sources:
  - name: br_rj_riodejaneiro_bilhetagem_staging
    database: rj-smtr-dev

    tables:
      - name: transacao
      - name: linha
      - name: grupo
      - name: grupo_linha
      - name: dicionario
      - name: consorcio
      - name: pessoa_juridica
      - name: operadora_transporte
      - name: ordem_pagamento
      - name: ordem_ressarcimento
      - name: linha_consorcio
      - name: conta_bancaria
      - name: contato_pessoa_juridica
      - name: cliente

  - name: br_rj_riodejaneiro_gtfs_staging
    database: rj-smtr-staging

    tables:
      - name: agency
      - name: calendar
      - name: calendar_dates
      - name: fare_attributes
      - name: fare_rules
      - name: feed_info
      - name: frequencies
      - name: routes
      - name: shapes
      - name: stops
      - name: stop_times
      - name: trips
      - name: ordem_servico

  - name: br_rj_riodejaneiro_stu_staging
    database: rj-smtr-dev
    
    tables:
      - name: operadora_empresa
      - name: operadora_pessoa_fisica
      
  - name: br_rj_riodejaneiro_recurso_staging
    database: rj-smtr-staging

    tables:
      - name: recurso_sppo