version: 2

sources:
  - name: br_rj_riodejaneiro_bilhetagem_staging
    database: rj-smtr-dev

    tables:
      - name: transacao
      - name: linha
      - name: grupo
      - name: grupo_linha
      - name: dicionario
      - name: consorcio
      - name: pessoa_juridica
      - name: operadora_transporte
      - name: ordem_pagamento
      - name: ordem_ressarcimento